const crosswordData = [
    {
        id: "crosswords/1",
        number: 1,
        name: "Crossword #1",
        dimensions: {
            cols: 11,
            rows: 11,
        },
        solutionAvailable: true,
        entries: [
            {
                id: "7-across",
                number: 7,
                humanNumber: "7",
                clue: "Left cheese out for worms (7)",
                direction: "across",
                length: 7,
                group: ["7-across"],
                position: { x: 0, y: 1 },
                separatorLocations: {},
                solution: "LEECHES"
            },
            {
                id: "8-across",
                number: 8,
                humanNumber: "8",
                clue: "See about old John (3)",
                direction: "across",
                length: 3,
                group: ["8-across"],
                position: { x: 8, y: 1 },
                separatorLocations: {},
                solution: "LOO"
            },
            {
                id: "9-across",
                number: 9,
                humanNumber: "9",
                clue: "Daring bachelor party (5)",
                direction: "across",
                length: 5,
                group: ["9-across"],
                position: { x: 0, y: 3 },
                separatorLocations: {},
                solution: "BRAVE"
            },
            {
                id: "10-across",
                number: 10,
                humanNumber: "10",
                clue: "Uniform patcher's heading for a superior (5)",
                direction: "across",
                length: 5,
                group: ["10-across"],
                position: { x: 6, y: 3 },
                separatorLocations: {},
                solution: "UPPER"
            },
            {
                id: "11-across",
                number: 11,
                humanNumber: "11",
                clue: "Rip off mini dress (5-6)",
                direction: "across",
                length: 11,
                group: ["11-across"],
                position: { x: 0, y: 5 },
                separatorLocations: { "-": [5] },
                solution: "SHORTCHANGE"
            },
            {
                id: "14-across",
                number: 14,
                humanNumber: "14",
                clue: "Frequently visit one found in search (5)",
                direction: "across",
                length: 5,
                group: ["14-across"],
                position: { x: 0, y: 7 },
                separatorLocations: {},
                solution: "HAUNT"
            },
            {
                id: "16-across",
                number: 16,
                humanNumber: "16",
                clue: "It's extracted from mines initially, and elsewhere (5)",
                direction: "across",
                length: 5,
                group: ["16-across"],
                position: { x: 6, y: 7 },
                separatorLocations: {},
                solution: "METAL"
            },
            {
                id: "18-across",
                number: 18,
                humanNumber: "18",
                clue: "Red onion exists primarily for eggs (3)",
                direction: "across",
                length: 3,
                group: ["18-across"],
                position: { x: 0, y: 9 },
                separatorLocations: {},
                solution: "ROE"
            },
            {
                id: "19-across",
                number: 19,
                humanNumber: "19",
                clue: "Newlywed after extremely likeable first-class luxury (7)",
                direction: "across",
                length: 7,
                group: ["19-across"],
                position: { x: 4, y: 9 },
                separatorLocations: {},
                solution: "LEGROOM"
            },
            {
                id: "1-down",
                number: 1,
                humanNumber: "1",
                clue: "Exclusive group member in a black suit (4)",
                direction: "down",
                length: 4,
                group: ["1-down"],
                position: { x: 0, y: 0 },
                separatorLocations: {},
                solution: "CLUB"
            },
            {
                id: "2-down",
                number: 2,
                humanNumber: "2",
                clue: "Gelato churned smoothly (6)",
                direction: "down",
                length: 6,
                group: ["2-down"],
                position: { x: 2, y: 0 },
                separatorLocations: {},
                solution: "LEGATO"
            },
            {
                id: "3-down",
                number: 3,
                humanNumber: "3",
                clue: "Half shoves head of elephant trainer? (4)",
                direction: "down",
                length: 4,
                group: ["3-down"],
                position: { x: 4, y: 0 },
                separatorLocations: {},
                solution: "SHOE"
            },
            {
                id: "4-down",
                number: 4,
                humanNumber: "4",
                clue: "In that regard, a swear word upset husband (2,4)",
                direction: "down",
                length: 6,
                group: ["4-down"],
                position: { x: 6, y: 0 },
                separatorLocations: { ",": [2] },
                solution: "ASSUCH"
            },
            {
                id: "5-down",
                number: 5,
                humanNumber: "5",
                clue: "Locked in pupil fixes up turn (4)",
                direction: "down",
                length: 4,
                group: ["5-down"],
                position: { x: 8, y: 0 },
                separatorLocations: {},
                solution: "FLIP"
            },
            {
                id: "6-down",
                number: 6,
                humanNumber: "6",
                clue: "Obscene programme broadcast (6)",
                direction: "down",
                length: 6,
                group: ["6-down"],
                position: { x: 10, y: 0 },
                separatorLocations: {},
                solution: "COARSE"
            },
            {
                id: "11-down",
                number: 11,
                humanNumber: "11",
                clue: "Ball sport's first duo in attendance (6)",
                direction: "down",
                length: 6,
                group: ["11-down"],
                position: { x: 0, y: 5 },
                separatorLocations: {},
                solution: "SPHERE"
            },
            {
                id: "12-down",
                number: 12,
                humanNumber: "12",
                clue: "Gossip time after time in story (6)",
                direction: "down",
                length: 6,
                group: ["12-down"],
                position: { x: 4, y: 5 },
                separatorLocations: {},
                solution: "TATTLE"
            },
            {
                id: "13-down",
                number: 13,
                humanNumber: "13",
                clue: "I put in unacceptable idea (6)",
                direction: "down",
                length: 6,
                group: ["13-down"],
                position: { x: 8, y: 5 },
                separatorLocations: {},
                solution: "NOTION"
            },
            {
                id: "15-down",
                number: 15,
                humanNumber: "15",
                clue: "Addict buys beer every second (4)",
                direction: "down",
                length: 4,
                group: ["15-down"],
                position: { x: 2, y: 7 },
                separatorLocations: {},
                solution: "USER"
            },
            {
                id: "16-down",
                number: 16,
                humanNumber: "16",
                clue: "Picture hiding one wizard (4)",
                direction: "down",
                length: 4,
                group: ["16-down"],
                position: { x: 6, y: 7 },
                separatorLocations: {},
                solution: "MAGE"
            },
            {
                id: "17-down",
                number: 17,
                humanNumber: "17",
                clue: "Go up, chopping first branch (4)",
                direction: "down",
                length: 4,
                group: ["17-down"],
                position: { x: 10, y: 7 },
                separatorLocations: {},
                solution: "LIMB"
            },
        ],
    },
];

export default crosswordData;
